import type { Metadata } from "next";
import "@/app/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen bg-slate-50">
      <Header />
      <Toaster />
      <main className="pt-16 lg:pt-20">{children}</main>

      <Footer />
    </div>
  );
}
